# Generated by Django 5.1.1 on 2024-10-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='movies', to='movie.director'),
        ),
    ]
